### ISSUE TITLE
priest gothik assigns

### ISSUE THREAD

**Issue by Mujobeng** [kallerotmg/AddOns#20]
Left Side: Priest 1 = (priest name) Priest 2 = (priest name) Priest 3 = (priest name)
Right Side:  Priest 1 = (priest name) Priest 2 = (priest name) Priest 3 = (priest name)

Just one example, you can probs write it in a "better" way..

**Comment by gimerstedt** [comment]
done:
https://github.com/kallerotmg/AddOns/commit/f9c0c89f3569d1b3b8e44bb29e19a4479cc5c998

**Comment by gimerstedt** [comment]
works as intended.
